#using node.js image to initialize a container 
FROM node:22-alpine

# creating a main directory
WORKDIR /app

# copy packages from the local files.  note-> * selects all the files that starts with package
COPY package*.json .  

# installing the dependencies
RUN npm install

# Copying all other files of the app
COPY . .

#exposing the post to run the app
EXPOSE 3003

#command to run the app
RUN ["node", "./src/server.js"]