### sending requests 

POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "username" : "testmail@gmail.com",
    "password":  "123456789"
}

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username" : "testmail@gmail.com",
    "password":  "123456789"
}


###

GET  http://localhost:3000/